server:
  port: 9192

spring:
  datasource:
    username: root
    password: hell0hell0Mysql
    url: jdbc:mysql://localhost:3312/db-spring-crud1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
